include: "/autogenerated_views/customer_order.view.lkml"
include: "/refined_views/customer_order_r.view.lkml"

explore: customer_order {
  fields: [customer_order.sales_document,
    customer_order.your_reference,
    customer_order.outlet_id,
    customer_order.created_date,
    customer_order.last_change_datetime_raw,
    customer_order.total_net_amount,
    customer_order.sold_to_party]
}
