include: "/autogenerated_views/da_seeburger.view.lkml"
include: "/refined_views/da_seeburger_all_r.view.lkml"

explore: +da_seeburger {
  hidden: no

  join: da_seeburger__master_shipment_container {
    view_label: "Da Seeburger: Mastershipmentcontainer"
    sql: LEFT JOIN UNNEST([${da_seeburger.master_shipment_container}]) as da_seeburger__master_shipment_container ;;
    relationship: one_to_many
  }

  join: da_seeburger__master_shipment_container__shipment_container__level {
    view_label: "Da Seeburger: Mastershipmentcontainer Shipmentcontainer Level"
    sql: left join UNNEST([${da_seeburger__master_shipment_container.shipment_container__level}]) as da_seeburger__master_shipment_container__shipment_container__level ;;
    relationship: one_to_many
  }

  join: da_seeburger__master_shipment_container__shipment_container__line_items {
    view_label: "Da Seeburger: Mastershipmentcontainer Shipmentcontainer Lineitems"
    sql: left join UNNEST([${da_seeburger__master_shipment_container.shipment_container__line_items}]) as da_seeburger__master_shipment_container__shipment_container__line_items ;;
    relationship: one_to_many
  }

  join: da_seeburger__master_shipment_container__shipment_container {
    view_label: "Da Seeburger: Mastershipmentcontainer Shipmentcontainer"
    sql: left join UNNEST([${da_seeburger__master_shipment_container.shipment_container}]) as da_seeburger__master_shipment_container__shipment_container ;;
    relationship: one_to_many
  }
}
