include: "/autogenerated_views/sales_order.view.lkml"
include: "/refined_views/sales_order_all_r.view.lkml"
include: "/derived_tables/anomaly_alert.view.lkml"

explore: +sales_order {
  hidden: no

  join: anomaly_alert {
    sql_on: ${sales_order.order_number} = ${anomaly_alert.sap_reference};;
    relationship: one_to_one
  }
}
