include: "/autogenerated_views/sales_order.view.lkml"
include: "/refined_views/sales_order_all_r.view.lkml"

explore: +sales_order {
  hidden: yes
  fields: [sales_order.delivery_details__delivery_type,
    sales_order.delivery_details__pickup_outlet_id,
    sales_order.order_number]
}
