connection: "poc_mms_bq"

include: "/autogenerated_views/**/*.view.lkml"
include: "/refined_views/**/*.view.lkml"
include: "/explores/**/*.explore.lkml"


datagroup: anomaly_alert {
  max_cache_age: "4 hours"
  sql_trigger: SELECT max(sales_document) FROM mms-plg-looker-poc-a.sales_order.sales_order ;;
  # You can use the optional interval_trigger subparameter to specify a time duration for rebuilding.
  # In the interval_trigger parameter you pass a string containing an integer followed by “seconds”, “minutes”, or “hours”.
  # interval_trigger: "12 hours"
  label: "Supply chain alert datagroup"
  description: "datagroup to rebuild anomaly_alert view every 24 hours or unless the max sales document number increases (assumes that every time an order is
  made a sales document number is generated and this increases in increments of 1"
}
