include: "/autogenerated_views/customer_order.view.lkml"

view: +customer_order {

  dimension: sales_document {
    label: "SAP Sales Document"
  }

  dimension: sap_outlet {
    label: "SAP Outlet"
    sql: right(${sold_to_party}, 3) ;;
  }

  dimension: your_reference {
    label: "SAP Reference"
  }

}
