include: "/autogenerated_views/da_seeburger.view.lkml"

view: +da_seeburger {
}

view: +da_seeburger__master_shipment_container {
}

view: +da_seeburger__master_shipment_container__shipment_container__level {
}

view: +da_seeburger__master_shipment_container__shipment_container__line_items {
}

view: +da_seeburger__master_shipment_container__shipment_container {
}
